//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EndeavorlinkStats.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class mg_senxxxual
    {
        public string UserNumber { get; set; }
        public string productCode { get; set; }
        public string ApplyTime { get; set; }
        public string ExpireTime { get; set; }
        public int SusbcriptionStatus { get; set; }
        public int Trial { get; set; }
        public int SubscriptionChannel { get; set; }
        public string UA { get; set; }
        public string BillingCycleStart { get; set; }
        public string BillingCycleEnd { get; set; }
        public string NextCharge { get; set; }
        public string rentStatus { get; set; }
    }
}
