//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EndeavorlinkStats.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class StatsContextContainer : DbContext
    {
        public StatsContextContainer()
            : base("name=StatsContextContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<mg_senxxxual> mg_senxxxual { get; set; }
        public DbSet<sysdiagram> sysdiagrams { get; set; }
        public DbSet<tbl_amdocs_dev2> tbl_amdocs_dev2 { get; set; }
        public DbSet<tbl_amdocs_device> tbl_amdocs_device { get; set; }
        public DbSet<tbl_amdocs_device2> tbl_amdocs_device2 { get; set; }
        public DbSet<tbl_ch> tbl_ch { get; set; }
        public DbSet<tbl_charge_peru> tbl_charge_peru { get; set; }
        public DbSet<tbl_charge_peru_claro> tbl_charge_peru_claro { get; set; }
        public DbSet<tbl_com_nobill> tbl_com_nobill { get; set; }
        public DbSet<tbl_comcel_charge> tbl_comcel_charge { get; set; }
        public DbSet<tbl_comcel_sub> tbl_comcel_sub { get; set; }
        public DbSet<tbl_comcel_sub_source> tbl_comcel_sub_source { get; set; }
        public DbSet<tbl_content_provider> tbl_content_provider { get; set; }
        public DbSet<tbl_cp_callback> tbl_cp_callback { get; set; }
        public DbSet<tbl_eng_charge> tbl_eng_charge { get; set; }
        public DbSet<tbl_eng_mo> tbl_eng_mo { get; set; }
        public DbSet<tbl_eng_mt> tbl_eng_mt { get; set; }
        public DbSet<tbl_eng_persistant_sub> tbl_eng_persistant_sub { get; set; }
        public DbSet<tbl_eng_subscription> tbl_eng_subscription { get; set; }
        public DbSet<tbl_eng_unsub> tbl_eng_unsub { get; set; }
        public DbSet<tbl_eng_unsub_notification> tbl_eng_unsub_notification { get; set; }
        public DbSet<tbl_fb_user> tbl_fb_user { get; set; }
        public DbSet<tbl_gm_catalog> tbl_gm_catalog { get; set; }
        public DbSet<tbl_gm_xendex_amdocs> tbl_gm_xendex_amdocs { get; set; }
        public DbSet<tbl_hub_sync> tbl_hub_sync { get; set; }
        public DbSet<tbl_ml_sms_prices> tbl_ml_sms_prices { get; set; }
        public DbSet<tbl_mlk_sms> tbl_mlk_sms { get; set; }
        public DbSet<tbl_mt_extern> tbl_mt_extern { get; set; }
        public DbSet<tbl_operator> tbl_operator { get; set; }
        public DbSet<tbl_pais> tbl_pais { get; set; }
        public DbSet<tbl_peru_ml_charge> tbl_peru_ml_charge { get; set; }
        public DbSet<tbl_peru_ml_subcription> tbl_peru_ml_subcription { get; set; }
        public DbSet<tbl_perums_callback> tbl_perums_callback { get; set; }
        public DbSet<tbl_pkaboo_bill> tbl_pkaboo_bill { get; set; }
        public DbSet<tbl_pkaboo_hit> tbl_pkaboo_hit { get; set; }
        public DbSet<tbl_pkaboo_start> tbl_pkaboo_start { get; set; }
        public DbSet<tbl_purebros_bill> tbl_purebros_bill { get; set; }
        public DbSet<tbl_purebros_mo> tbl_purebros_mo { get; set; }
        public DbSet<tbl_purebros_mt> tbl_purebros_mt { get; set; }
        public DbSet<tbl_service> tbl_service { get; set; }
        public DbSet<TBL_SFM> TBL_SFM { get; set; }
        public DbSet<tbl_sia_billing> tbl_sia_billing { get; set; }
        public DbSet<tbl_sia_block> tbl_sia_block { get; set; }
        public DbSet<tbl_sia_block_2> tbl_sia_block_2 { get; set; }
        public DbSet<tbl_sia_distinct_transaction> tbl_sia_distinct_transaction { get; set; }
        public DbSet<tbl_sia_msenxxxual> tbl_sia_msenxxxual { get; set; }
        public DbSet<tbl_sia_msenxxxual_p2> tbl_sia_msenxxxual_p2 { get; set; }
        public DbSet<tbl_sia_msenxxxual_simple> tbl_sia_msenxxxual_simple { get; set; }
        public DbSet<tbl_sia_msenxxxual_simple2> tbl_sia_msenxxxual_simple2 { get; set; }
        public DbSet<tbl_sia_msenxxxual_simples> tbl_sia_msenxxxual_simples { get; set; }
        public DbSet<tbl_sia_msenxxxualn> tbl_sia_msenxxxualn { get; set; }
        public DbSet<tbl_sia_msenxxxualp> tbl_sia_msenxxxualp { get; set; }
        public DbSet<tbl_sia_sf_migrated> tbl_sia_sf_migrated { get; set; }
        public DbSet<tbl_sia_transaction> tbl_sia_transaction { get; set; }
        public DbSet<tbl_sms_mo> tbl_sms_mo { get; set; }
        public DbSet<tbl_sms_mo_deliver> tbl_sms_mo_deliver { get; set; }
        public DbSet<tbl_sms_mt> tbl_sms_mt { get; set; }
        public DbSet<tbl_sms_mt_log> tbl_sms_mt_log { get; set; }
        public DbSet<tbl_sms_sc> tbl_sms_sc { get; set; }
        public DbSet<tbl_sms_sc_url> tbl_sms_sc_url { get; set; }
        public DbSet<tbl_smt_serviceid> tbl_smt_serviceid { get; set; }
        public DbSet<tbl_smt_sub> tbl_smt_sub { get; set; }
        public DbSet<tbl_user> tbl_user { get; set; }
        public DbSet<tbl_user_operator> tbl_user_operator { get; set; }
        public DbSet<tbl_xendex_ua> tbl_xendex_ua { get; set; }
    
        public virtual ObjectResult<sp_stats_getMovistarMonthByUser_Result> sp_stats_getMovistarMonthByUser(Nullable<decimal> id_user, Nullable<decimal> selected_year, Nullable<decimal> selected_month)
        {
            var id_userParameter = id_user.HasValue ?
                new ObjectParameter("id_user", id_user) :
                new ObjectParameter("id_user", typeof(decimal));
    
            var selected_yearParameter = selected_year.HasValue ?
                new ObjectParameter("selected_year", selected_year) :
                new ObjectParameter("selected_year", typeof(decimal));
    
            var selected_monthParameter = selected_month.HasValue ?
                new ObjectParameter("selected_month", selected_month) :
                new ObjectParameter("selected_month", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_stats_getMovistarMonthByUser_Result>("sp_stats_getMovistarMonthByUser", id_userParameter, selected_yearParameter, selected_monthParameter);
        }
    
        public virtual ObjectResult<sp_get_user_operator_Result> sp_get_user_operator(Nullable<decimal> id_user)
        {
            var id_userParameter = id_user.HasValue ?
                new ObjectParameter("id_user", id_user) :
                new ObjectParameter("id_user", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_get_user_operator_Result>("sp_get_user_operator", id_userParameter);
        }
    
        public virtual ObjectResult<sp_stats_getComcelStatsByUserId_Result> sp_stats_getComcelStatsByUserId(Nullable<decimal> anio, Nullable<decimal> mes, Nullable<decimal> id_user)
        {
            var anioParameter = anio.HasValue ?
                new ObjectParameter("anio", anio) :
                new ObjectParameter("anio", typeof(decimal));
    
            var mesParameter = mes.HasValue ?
                new ObjectParameter("mes", mes) :
                new ObjectParameter("mes", typeof(decimal));
    
            var id_userParameter = id_user.HasValue ?
                new ObjectParameter("id_user", id_user) :
                new ObjectParameter("id_user", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_stats_getComcelStatsByUserId_Result>("sp_stats_getComcelStatsByUserId", anioParameter, mesParameter, id_userParameter);
        }
    
        public virtual ObjectResult<sp_stats_getClaroMonthByUserId_Result> sp_stats_getClaroMonthByUserId(Nullable<decimal> mes, Nullable<decimal> anho, Nullable<decimal> id_user)
        {
            var mesParameter = mes.HasValue ?
                new ObjectParameter("mes", mes) :
                new ObjectParameter("mes", typeof(decimal));
    
            var anhoParameter = anho.HasValue ?
                new ObjectParameter("anho", anho) :
                new ObjectParameter("anho", typeof(decimal));
    
            var id_userParameter = id_user.HasValue ?
                new ObjectParameter("id_user", id_user) :
                new ObjectParameter("id_user", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_stats_getClaroMonthByUserId_Result>("sp_stats_getClaroMonthByUserId", mesParameter, anhoParameter, id_userParameter);
        }
    
        public virtual ObjectResult<sp_get_claro_stats_Result> sp_get_claro_stats(Nullable<decimal> mes, Nullable<decimal> anho)
        {
            var mesParameter = mes.HasValue ?
                new ObjectParameter("mes", mes) :
                new ObjectParameter("mes", typeof(decimal));
    
            var anhoParameter = anho.HasValue ?
                new ObjectParameter("anho", anho) :
                new ObjectParameter("anho", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_get_claro_stats_Result>("sp_get_claro_stats", mesParameter, anhoParameter);
        }
    
        public virtual ObjectResult<sp_getClaroStatsMonth_Result> sp_getClaroStatsMonth(Nullable<int> mes, Nullable<int> anho, string user)
        {
            var mesParameter = mes.HasValue ?
                new ObjectParameter("mes", mes) :
                new ObjectParameter("mes", typeof(int));
    
            var anhoParameter = anho.HasValue ?
                new ObjectParameter("anho", anho) :
                new ObjectParameter("anho", typeof(int));
    
            var userParameter = user != null ?
                new ObjectParameter("user", user) :
                new ObjectParameter("user", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_getClaroStatsMonth_Result>("sp_getClaroStatsMonth", mesParameter, anhoParameter, userParameter);
        }
    
        public virtual ObjectResult<sp_perums_getStats_Result> sp_perums_getStats(Nullable<decimal> selected_year, Nullable<decimal> selected_month)
        {
            var selected_yearParameter = selected_year.HasValue ?
                new ObjectParameter("selected_year", selected_year) :
                new ObjectParameter("selected_year", typeof(decimal));
    
            var selected_monthParameter = selected_month.HasValue ?
                new ObjectParameter("selected_month", selected_month) :
                new ObjectParameter("selected_month", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_perums_getStats_Result>("sp_perums_getStats", selected_yearParameter, selected_monthParameter);
        }
    
        public virtual ObjectResult<sp_perums_getStats_month_Result> sp_perums_getStats_month(Nullable<decimal> year, Nullable<decimal> mes, string subservice_code)
        {
            var yearParameter = year.HasValue ?
                new ObjectParameter("year", year) :
                new ObjectParameter("year", typeof(decimal));
    
            var mesParameter = mes.HasValue ?
                new ObjectParameter("mes", mes) :
                new ObjectParameter("mes", typeof(decimal));
    
            var subservice_codeParameter = subservice_code != null ?
                new ObjectParameter("subservice_code", subservice_code) :
                new ObjectParameter("subservice_code", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_perums_getStats_month_Result>("sp_perums_getStats_month", yearParameter, mesParameter, subservice_codeParameter);
        }
    
        public virtual ObjectResult<sp_rpt_comcel_Result> sp_rpt_comcel(Nullable<decimal> mes)
        {
            var mesParameter = mes.HasValue ?
                new ObjectParameter("mes", mes) :
                new ObjectParameter("mes", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_rpt_comcel_Result>("sp_rpt_comcel", mesParameter);
        }
    
        public virtual ObjectResult<sp_rpt_comcel_month_Result> sp_rpt_comcel_month(Nullable<decimal> mes)
        {
            var mesParameter = mes.HasValue ?
                new ObjectParameter("mes", mes) :
                new ObjectParameter("mes", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_rpt_comcel_month_Result>("sp_rpt_comcel_month", mesParameter);
        }
    
        public virtual ObjectResult<sp_stats_getComcelAdmin_Result> sp_stats_getComcelAdmin(Nullable<decimal> anio, Nullable<decimal> mes)
        {
            var anioParameter = anio.HasValue ?
                new ObjectParameter("anio", anio) :
                new ObjectParameter("anio", typeof(decimal));
    
            var mesParameter = mes.HasValue ?
                new ObjectParameter("mes", mes) :
                new ObjectParameter("mes", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_stats_getComcelAdmin_Result>("sp_stats_getComcelAdmin", anioParameter, mesParameter);
        }
    
        public virtual ObjectResult<sp_get_mo_support_Result> sp_get_mo_support(string msisdn)
        {
            var msisdnParameter = msisdn != null ?
                new ObjectParameter("msisdn", msisdn) :
                new ObjectParameter("msisdn", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_get_mo_support_Result>("sp_get_mo_support", msisdnParameter);
        }
    
        public virtual ObjectResult<sp_get_mt_support_Result> sp_get_mt_support(string msisdn)
        {
            var msisdnParameter = msisdn != null ?
                new ObjectParameter("msisdn", msisdn) :
                new ObjectParameter("msisdn", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_get_mt_support_Result>("sp_get_mt_support", msisdnParameter);
        }
    
        public virtual int sp_sms_ins_mo(Nullable<decimal> id_sc, string msg, Nullable<decimal> msisdn, ObjectParameter id_mo)
        {
            var id_scParameter = id_sc.HasValue ?
                new ObjectParameter("id_sc", id_sc) :
                new ObjectParameter("id_sc", typeof(decimal));
    
            var msgParameter = msg != null ?
                new ObjectParameter("msg", msg) :
                new ObjectParameter("msg", typeof(string));
    
            var msisdnParameter = msisdn.HasValue ?
                new ObjectParameter("msisdn", msisdn) :
                new ObjectParameter("msisdn", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_sms_ins_mo", id_scParameter, msgParameter, msisdnParameter, id_mo);
        }
    
        public virtual int sp_sms_ins_mt(string id_ex, Nullable<decimal> id_user, Nullable<decimal> msisdn, string msg, string title, Nullable<decimal> id_sc, string smstype, ObjectParameter id)
        {
            var id_exParameter = id_ex != null ?
                new ObjectParameter("id_ex", id_ex) :
                new ObjectParameter("id_ex", typeof(string));
    
            var id_userParameter = id_user.HasValue ?
                new ObjectParameter("id_user", id_user) :
                new ObjectParameter("id_user", typeof(decimal));
    
            var msisdnParameter = msisdn.HasValue ?
                new ObjectParameter("msisdn", msisdn) :
                new ObjectParameter("msisdn", typeof(decimal));
    
            var msgParameter = msg != null ?
                new ObjectParameter("msg", msg) :
                new ObjectParameter("msg", typeof(string));
    
            var titleParameter = title != null ?
                new ObjectParameter("title", title) :
                new ObjectParameter("title", typeof(string));
    
            var id_scParameter = id_sc.HasValue ?
                new ObjectParameter("id_sc", id_sc) :
                new ObjectParameter("id_sc", typeof(decimal));
    
            var smstypeParameter = smstype != null ?
                new ObjectParameter("smstype", smstype) :
                new ObjectParameter("smstype", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_sms_ins_mt", id_exParameter, id_userParameter, msisdnParameter, msgParameter, titleParameter, id_scParameter, smstypeParameter, id);
        }
    
        public virtual int sp_inject_mo(Nullable<decimal> id_sc, string msg, Nullable<decimal> msisdn)
        {
            var id_scParameter = id_sc.HasValue ?
                new ObjectParameter("id_sc", id_sc) :
                new ObjectParameter("id_sc", typeof(decimal));
    
            var msgParameter = msg != null ?
                new ObjectParameter("msg", msg) :
                new ObjectParameter("msg", typeof(string));
    
            var msisdnParameter = msisdn.HasValue ?
                new ObjectParameter("msisdn", msisdn) :
                new ObjectParameter("msisdn", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_inject_mo", id_scParameter, msgParameter, msisdnParameter);
        }
    
        public virtual int sp_inject_mt(string id_ex, Nullable<decimal> id_user, Nullable<decimal> msisdn, string msg, string title, Nullable<decimal> id_sc, string smstype)
        {
            var id_exParameter = id_ex != null ?
                new ObjectParameter("id_ex", id_ex) :
                new ObjectParameter("id_ex", typeof(string));
    
            var id_userParameter = id_user.HasValue ?
                new ObjectParameter("id_user", id_user) :
                new ObjectParameter("id_user", typeof(decimal));
    
            var msisdnParameter = msisdn.HasValue ?
                new ObjectParameter("msisdn", msisdn) :
                new ObjectParameter("msisdn", typeof(decimal));
    
            var msgParameter = msg != null ?
                new ObjectParameter("msg", msg) :
                new ObjectParameter("msg", typeof(string));
    
            var titleParameter = title != null ?
                new ObjectParameter("title", title) :
                new ObjectParameter("title", typeof(string));
    
            var id_scParameter = id_sc.HasValue ?
                new ObjectParameter("id_sc", id_sc) :
                new ObjectParameter("id_sc", typeof(decimal));
    
            var smstypeParameter = smstype != null ?
                new ObjectParameter("smstype", smstype) :
                new ObjectParameter("smstype", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_inject_mt", id_exParameter, id_userParameter, msisdnParameter, msgParameter, titleParameter, id_scParameter, smstypeParameter);
        }
    
        public virtual ObjectResult<sp_get_movistar_anual_Result> sp_get_movistar_anual(Nullable<decimal> anio, Nullable<decimal> id_user)
        {
            var anioParameter = anio.HasValue ?
                new ObjectParameter("anio", anio) :
                new ObjectParameter("anio", typeof(decimal));
    
            var id_userParameter = id_user.HasValue ?
                new ObjectParameter("id_user", id_user) :
                new ObjectParameter("id_user", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_get_movistar_anual_Result>("sp_get_movistar_anual", anioParameter, id_userParameter);
        }
    
        public virtual ObjectResult<sp_get_claro_anual_Result> sp_get_claro_anual(Nullable<decimal> anio, Nullable<decimal> id_user)
        {
            var anioParameter = anio.HasValue ?
                new ObjectParameter("anio", anio) :
                new ObjectParameter("anio", typeof(decimal));
    
            var id_userParameter = id_user.HasValue ?
                new ObjectParameter("id_user", id_user) :
                new ObjectParameter("id_user", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_get_claro_anual_Result>("sp_get_claro_anual", anioParameter, id_userParameter);
        }
    
        public virtual ObjectResult<sp_get_comcel_anual_Result> sp_get_comcel_anual(Nullable<decimal> anio, Nullable<decimal> id_user)
        {
            var anioParameter = anio.HasValue ?
                new ObjectParameter("anio", anio) :
                new ObjectParameter("anio", typeof(decimal));
    
            var id_userParameter = id_user.HasValue ?
                new ObjectParameter("id_user", id_user) :
                new ObjectParameter("id_user", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_get_comcel_anual_Result>("sp_get_comcel_anual", anioParameter, id_userParameter);
        }
    
        public virtual ObjectResult<sp_get_mt_support_Result> sp_get_mt_support_log(string msisdn)
        {
            var msisdnParameter = msisdn != null ?
                new ObjectParameter("msisdn", msisdn) :
                new ObjectParameter("msisdn", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_get_mt_support_Result>("sp_get_mt_support_log", msisdnParameter);
        }
    }
}
