//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EndeavorlinkStats.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class smartg : DbContext
    {
        public smartg()
            : base("name=smartg")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<mg_senxxxual> mg_senxxxual { get; set; }
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
        public DbSet<tbl_amdocs_dev2> tbl_amdocs_dev2 { get; set; }
        public DbSet<tbl_amdocs_device> tbl_amdocs_device { get; set; }
        public DbSet<tbl_amdocs_device2> tbl_amdocs_device2 { get; set; }
        public DbSet<tbl_ch> tbl_ch { get; set; }
        public DbSet<tbl_charge_peru> tbl_charge_peru { get; set; }
        public DbSet<tbl_charge_peru_claro> tbl_charge_peru_claro { get; set; }
        public DbSet<tbl_com_nobill> tbl_com_nobill { get; set; }
        public DbSet<tbl_comcel_charge> tbl_comcel_charge { get; set; }
        public DbSet<tbl_comcel_sub> tbl_comcel_sub { get; set; }
        public DbSet<tbl_comcel_sub_source> tbl_comcel_sub_source { get; set; }
        public DbSet<tbl_content_provider> tbl_content_provider { get; set; }
        public DbSet<tbl_cp_callback> tbl_cp_callback { get; set; }
        public DbSet<tbl_eng_charge> tbl_eng_charge { get; set; }
        public DbSet<tbl_eng_mo> tbl_eng_mo { get; set; }
        public DbSet<tbl_eng_mt> tbl_eng_mt { get; set; }
        public DbSet<tbl_eng_persistant_sub> tbl_eng_persistant_sub { get; set; }
        public DbSet<tbl_eng_subscription> tbl_eng_subscription { get; set; }
        public DbSet<tbl_eng_unsub> tbl_eng_unsub { get; set; }
        public DbSet<tbl_eng_unsub_notification> tbl_eng_unsub_notification { get; set; }
        public DbSet<tbl_fb_user> tbl_fb_user { get; set; }
        public DbSet<tbl_gm_catalog> tbl_gm_catalog { get; set; }
        public DbSet<tbl_gm_xendex_amdocs> tbl_gm_xendex_amdocs { get; set; }
        public DbSet<tbl_hub_sync> tbl_hub_sync { get; set; }
        public DbSet<tbl_ml_sms_prices> tbl_ml_sms_prices { get; set; }
        public DbSet<tbl_mlk_sms> tbl_mlk_sms { get; set; }
        public DbSet<tbl_mt_extern> tbl_mt_extern { get; set; }
        public DbSet<tbl_operator> tbl_operator { get; set; }
        public DbSet<tbl_peru_ml_charge> tbl_peru_ml_charge { get; set; }
        public DbSet<tbl_peru_ml_subcription> tbl_peru_ml_subcription { get; set; }
        public DbSet<tbl_perums_callback> tbl_perums_callback { get; set; }
        public DbSet<tbl_pkaboo_bill> tbl_pkaboo_bill { get; set; }
        public DbSet<tbl_pkaboo_hit> tbl_pkaboo_hit { get; set; }
        public DbSet<tbl_pkaboo_start> tbl_pkaboo_start { get; set; }
        public DbSet<tbl_purebros_bill> tbl_purebros_bill { get; set; }
        public DbSet<tbl_purebros_mo> tbl_purebros_mo { get; set; }
        public DbSet<tbl_purebros_mt> tbl_purebros_mt { get; set; }
        public DbSet<tbl_service> tbl_service { get; set; }
        public DbSet<TBL_SFM> TBL_SFM { get; set; }
        public DbSet<tbl_sia_billing> tbl_sia_billing { get; set; }
        public DbSet<tbl_sia_block> tbl_sia_block { get; set; }
        public DbSet<tbl_sia_block_2> tbl_sia_block_2 { get; set; }
        public DbSet<tbl_sia_distinct_transaction> tbl_sia_distinct_transaction { get; set; }
        public DbSet<tbl_sia_msenxxxual> tbl_sia_msenxxxual { get; set; }
        public DbSet<tbl_sia_msenxxxual_p2> tbl_sia_msenxxxual_p2 { get; set; }
        public DbSet<tbl_sia_msenxxxual_simple> tbl_sia_msenxxxual_simple { get; set; }
        public DbSet<tbl_sia_msenxxxual_simple2> tbl_sia_msenxxxual_simple2 { get; set; }
        public DbSet<tbl_sia_msenxxxual_simples> tbl_sia_msenxxxual_simples { get; set; }
        public DbSet<tbl_sia_msenxxxualn> tbl_sia_msenxxxualn { get; set; }
        public DbSet<tbl_sia_msenxxxualp> tbl_sia_msenxxxualp { get; set; }
        public DbSet<tbl_sia_transaction> tbl_sia_transaction { get; set; }
        public DbSet<tbl_sms_mo> tbl_sms_mo { get; set; }
        public DbSet<tbl_sms_mo_deliver> tbl_sms_mo_deliver { get; set; }
        public DbSet<tbl_sms_mt> tbl_sms_mt { get; set; }
        public DbSet<tbl_sms_mt_log> tbl_sms_mt_log { get; set; }
        public DbSet<tbl_sms_sc> tbl_sms_sc { get; set; }
        public DbSet<tbl_sms_sc_url> tbl_sms_sc_url { get; set; }
        public DbSet<tbl_smt_sub> tbl_smt_sub { get; set; }
        public DbSet<tbl_user> tbl_user { get; set; }
        public DbSet<tbl_xendex_ua> tbl_xendex_ua { get; set; }
        public DbSet<tbl_user_operator> tbl_user_operator { get; set; }
    
        public virtual int sp_addextendedproc(string functname, string dllname)
        {
            var functnameParameter = functname != null ?
                new ObjectParameter("functname", functname) :
                new ObjectParameter("functname", typeof(string));
    
            var dllnameParameter = dllname != null ?
                new ObjectParameter("dllname", dllname) :
                new ObjectParameter("dllname", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_addextendedproc", functnameParameter, dllnameParameter);
        }
    
        public virtual int sp_alterdiagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_alterdiagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual ObjectResult<sp_comcel_renew_Result> sp_comcel_renew()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_comcel_renew_Result>("sp_comcel_renew");
        }
    
        public virtual int sp_creatediagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_creatediagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_dropdiagram(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_dropdiagram", diagramnameParameter, owner_idParameter);
        }
    
        public virtual int sp_eng_get_renew()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_eng_get_renew");
        }
    
        public virtual int sp_eng_get_renew_by_service(string serviceId)
        {
            var serviceIdParameter = serviceId != null ?
                new ObjectParameter("serviceId", serviceId) :
                new ObjectParameter("serviceId", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_eng_get_renew_by_service", serviceIdParameter);
        }
    
        public virtual int sp_eng_get_renew_by_service_pending(string serviceId)
        {
            var serviceIdParameter = serviceId != null ?
                new ObjectParameter("serviceId", serviceId) :
                new ObjectParameter("serviceId", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_eng_get_renew_by_service_pending", serviceIdParameter);
        }
    
        public virtual int sp_fb_ins_user(string token, Nullable<int> fbuser_id, Nullable<decimal> expirate, string fb_status)
        {
            var tokenParameter = token != null ?
                new ObjectParameter("token", token) :
                new ObjectParameter("token", typeof(string));
    
            var fbuser_idParameter = fbuser_id.HasValue ?
                new ObjectParameter("fbuser_id", fbuser_id) :
                new ObjectParameter("fbuser_id", typeof(int));
    
            var expirateParameter = expirate.HasValue ?
                new ObjectParameter("expirate", expirate) :
                new ObjectParameter("expirate", typeof(decimal));
    
            var fb_statusParameter = fb_status != null ?
                new ObjectParameter("fb_status", fb_status) :
                new ObjectParameter("fb_status", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_fb_ins_user", tokenParameter, fbuser_idParameter, expirateParameter, fb_statusParameter);
        }
    
        public virtual ObjectResult<string> sp_get_callback(Nullable<decimal> id_charge)
        {
            var id_chargeParameter = id_charge.HasValue ?
                new ObjectParameter("id_charge", id_charge) :
                new ObjectParameter("id_charge", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("sp_get_callback", id_chargeParameter);
        }
    
        public virtual ObjectResult<sp_get_claro_stats_Result> sp_get_claro_stats(Nullable<decimal> mes, Nullable<decimal> anho)
        {
            var mesParameter = mes.HasValue ?
                new ObjectParameter("mes", mes) :
                new ObjectParameter("mes", typeof(decimal));
    
            var anhoParameter = anho.HasValue ?
                new ObjectParameter("anho", anho) :
                new ObjectParameter("anho", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_get_claro_stats_Result>("sp_get_claro_stats", mesParameter, anhoParameter);
        }
    
        public virtual ObjectResult<sp_get_comcel_sub_Result> sp_get_comcel_sub(Nullable<decimal> id_user, Nullable<decimal> msisdn, Nullable<decimal> serviceCode, Nullable<decimal> providerCode)
        {
            var id_userParameter = id_user.HasValue ?
                new ObjectParameter("id_user", id_user) :
                new ObjectParameter("id_user", typeof(decimal));
    
            var msisdnParameter = msisdn.HasValue ?
                new ObjectParameter("msisdn", msisdn) :
                new ObjectParameter("msisdn", typeof(decimal));
    
            var serviceCodeParameter = serviceCode.HasValue ?
                new ObjectParameter("serviceCode", serviceCode) :
                new ObjectParameter("serviceCode", typeof(decimal));
    
            var providerCodeParameter = providerCode.HasValue ?
                new ObjectParameter("providerCode", providerCode) :
                new ObjectParameter("providerCode", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_get_comcel_sub_Result>("sp_get_comcel_sub", id_userParameter, msisdnParameter, serviceCodeParameter, providerCodeParameter);
        }
    
        public virtual ObjectResult<sp_getClaroStatsMonth_Result> sp_getClaroStatsMonth(Nullable<int> mes, Nullable<int> anho, string user)
        {
            var mesParameter = mes.HasValue ?
                new ObjectParameter("mes", mes) :
                new ObjectParameter("mes", typeof(int));
    
            var anhoParameter = anho.HasValue ?
                new ObjectParameter("anho", anho) :
                new ObjectParameter("anho", typeof(int));
    
            var userParameter = user != null ?
                new ObjectParameter("user", user) :
                new ObjectParameter("user", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_getClaroStatsMonth_Result>("sp_getClaroStatsMonth", mesParameter, anhoParameter, userParameter);
        }
    
        public virtual int sp_helpdiagramdefinition(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_helpdiagramdefinition", diagramnameParameter, owner_idParameter);
        }
    
        public virtual int sp_helpdiagrams(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_helpdiagrams", diagramnameParameter, owner_idParameter);
        }
    
        public virtual int sp_hub_save_sync(string msisdn, string spid, string serviceid, Nullable<decimal> updatetype, Nullable<decimal> rentResult, ObjectParameter id)
        {
            var msisdnParameter = msisdn != null ?
                new ObjectParameter("msisdn", msisdn) :
                new ObjectParameter("msisdn", typeof(string));
    
            var spidParameter = spid != null ?
                new ObjectParameter("spid", spid) :
                new ObjectParameter("spid", typeof(string));
    
            var serviceidParameter = serviceid != null ?
                new ObjectParameter("serviceid", serviceid) :
                new ObjectParameter("serviceid", typeof(string));
    
            var updatetypeParameter = updatetype.HasValue ?
                new ObjectParameter("updatetype", updatetype) :
                new ObjectParameter("updatetype", typeof(decimal));
    
            var rentResultParameter = rentResult.HasValue ?
                new ObjectParameter("rentResult", rentResult) :
                new ObjectParameter("rentResult", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_hub_save_sync", msisdnParameter, spidParameter, serviceidParameter, updatetypeParameter, rentResultParameter, id);
        }
    
        public virtual int sp_ins_charge_peru(Nullable<decimal> id_user, Nullable<decimal> operador, Nullable<decimal> msisdn, string serviceCode, string subserviceCode, string content_id, ObjectParameter id, Nullable<decimal> partnerID)
        {
            var id_userParameter = id_user.HasValue ?
                new ObjectParameter("id_user", id_user) :
                new ObjectParameter("id_user", typeof(decimal));
    
            var operadorParameter = operador.HasValue ?
                new ObjectParameter("operador", operador) :
                new ObjectParameter("operador", typeof(decimal));
    
            var msisdnParameter = msisdn.HasValue ?
                new ObjectParameter("msisdn", msisdn) :
                new ObjectParameter("msisdn", typeof(decimal));
    
            var serviceCodeParameter = serviceCode != null ?
                new ObjectParameter("serviceCode", serviceCode) :
                new ObjectParameter("serviceCode", typeof(string));
    
            var subserviceCodeParameter = subserviceCode != null ?
                new ObjectParameter("subserviceCode", subserviceCode) :
                new ObjectParameter("subserviceCode", typeof(string));
    
            var content_idParameter = content_id != null ?
                new ObjectParameter("content_id", content_id) :
                new ObjectParameter("content_id", typeof(string));
    
            var partnerIDParameter = partnerID.HasValue ?
                new ObjectParameter("partnerID", partnerID) :
                new ObjectParameter("partnerID", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ins_charge_peru", id_userParameter, operadorParameter, msisdnParameter, serviceCodeParameter, subserviceCodeParameter, content_idParameter, id, partnerIDParameter);
        }
    
        public virtual int sp_ins_comcel_charge(string idcp, Nullable<decimal> id_user, Nullable<decimal> msisdn, Nullable<decimal> serviceCode, Nullable<decimal> providerCode, string contentId, Nullable<decimal> response, string charge_type, ObjectParameter id)
        {
            var idcpParameter = idcp != null ?
                new ObjectParameter("idcp", idcp) :
                new ObjectParameter("idcp", typeof(string));
    
            var id_userParameter = id_user.HasValue ?
                new ObjectParameter("id_user", id_user) :
                new ObjectParameter("id_user", typeof(decimal));
    
            var msisdnParameter = msisdn.HasValue ?
                new ObjectParameter("msisdn", msisdn) :
                new ObjectParameter("msisdn", typeof(decimal));
    
            var serviceCodeParameter = serviceCode.HasValue ?
                new ObjectParameter("serviceCode", serviceCode) :
                new ObjectParameter("serviceCode", typeof(decimal));
    
            var providerCodeParameter = providerCode.HasValue ?
                new ObjectParameter("providerCode", providerCode) :
                new ObjectParameter("providerCode", typeof(decimal));
    
            var contentIdParameter = contentId != null ?
                new ObjectParameter("contentId", contentId) :
                new ObjectParameter("contentId", typeof(string));
    
            var responseParameter = response.HasValue ?
                new ObjectParameter("response", response) :
                new ObjectParameter("response", typeof(decimal));
    
            var charge_typeParameter = charge_type != null ?
                new ObjectParameter("charge_type", charge_type) :
                new ObjectParameter("charge_type", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ins_comcel_charge", idcpParameter, id_userParameter, msisdnParameter, serviceCodeParameter, providerCodeParameter, contentIdParameter, responseParameter, charge_typeParameter, id);
        }
    
        public virtual int sp_ins_comcel_sub(Nullable<decimal> id_user, Nullable<decimal> msisdn, Nullable<decimal> serviceCode, Nullable<decimal> providerCode, string sub_status, string idcp, ObjectParameter id)
        {
            var id_userParameter = id_user.HasValue ?
                new ObjectParameter("id_user", id_user) :
                new ObjectParameter("id_user", typeof(decimal));
    
            var msisdnParameter = msisdn.HasValue ?
                new ObjectParameter("msisdn", msisdn) :
                new ObjectParameter("msisdn", typeof(decimal));
    
            var serviceCodeParameter = serviceCode.HasValue ?
                new ObjectParameter("serviceCode", serviceCode) :
                new ObjectParameter("serviceCode", typeof(decimal));
    
            var providerCodeParameter = providerCode.HasValue ?
                new ObjectParameter("providerCode", providerCode) :
                new ObjectParameter("providerCode", typeof(decimal));
    
            var sub_statusParameter = sub_status != null ?
                new ObjectParameter("sub_status", sub_status) :
                new ObjectParameter("sub_status", typeof(string));
    
            var idcpParameter = idcp != null ?
                new ObjectParameter("idcp", idcp) :
                new ObjectParameter("idcp", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ins_comcel_sub", id_userParameter, msisdnParameter, serviceCodeParameter, providerCodeParameter, sub_statusParameter, idcpParameter, id);
        }
    
        public virtual int sp_ins_eng_charge(string txid, string serviceId, Nullable<decimal> authid, string cents, string chargeReason, string resultcode)
        {
            var txidParameter = txid != null ?
                new ObjectParameter("txid", txid) :
                new ObjectParameter("txid", typeof(string));
    
            var serviceIdParameter = serviceId != null ?
                new ObjectParameter("serviceId", serviceId) :
                new ObjectParameter("serviceId", typeof(string));
    
            var authidParameter = authid.HasValue ?
                new ObjectParameter("authid", authid) :
                new ObjectParameter("authid", typeof(decimal));
    
            var centsParameter = cents != null ?
                new ObjectParameter("cents", cents) :
                new ObjectParameter("cents", typeof(string));
    
            var chargeReasonParameter = chargeReason != null ?
                new ObjectParameter("chargeReason", chargeReason) :
                new ObjectParameter("chargeReason", typeof(string));
    
            var resultcodeParameter = resultcode != null ?
                new ObjectParameter("resultcode", resultcode) :
                new ObjectParameter("resultcode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ins_eng_charge", txidParameter, serviceIdParameter, authidParameter, centsParameter, chargeReasonParameter, resultcodeParameter);
        }
    
        public virtual int sp_ins_eng_oneshot(string txid, string serviceId, string operatorId, string categoryId, string msisdn, string channel, Nullable<decimal> authid, string protocolNumber, string resultcode)
        {
            var txidParameter = txid != null ?
                new ObjectParameter("txid", txid) :
                new ObjectParameter("txid", typeof(string));
    
            var serviceIdParameter = serviceId != null ?
                new ObjectParameter("serviceId", serviceId) :
                new ObjectParameter("serviceId", typeof(string));
    
            var operatorIdParameter = operatorId != null ?
                new ObjectParameter("operatorId", operatorId) :
                new ObjectParameter("operatorId", typeof(string));
    
            var categoryIdParameter = categoryId != null ?
                new ObjectParameter("categoryId", categoryId) :
                new ObjectParameter("categoryId", typeof(string));
    
            var msisdnParameter = msisdn != null ?
                new ObjectParameter("msisdn", msisdn) :
                new ObjectParameter("msisdn", typeof(string));
    
            var channelParameter = channel != null ?
                new ObjectParameter("channel", channel) :
                new ObjectParameter("channel", typeof(string));
    
            var authidParameter = authid.HasValue ?
                new ObjectParameter("authid", authid) :
                new ObjectParameter("authid", typeof(decimal));
    
            var protocolNumberParameter = protocolNumber != null ?
                new ObjectParameter("protocolNumber", protocolNumber) :
                new ObjectParameter("protocolNumber", typeof(string));
    
            var resultcodeParameter = resultcode != null ?
                new ObjectParameter("resultcode", resultcode) :
                new ObjectParameter("resultcode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ins_eng_oneshot", txidParameter, serviceIdParameter, operatorIdParameter, categoryIdParameter, msisdnParameter, channelParameter, authidParameter, protocolNumberParameter, resultcodeParameter);
        }
    
        public virtual int sp_ins_eng_sub(string txid, string serviceId, string operatorId, string categoryId, string msisdn, string channel, Nullable<decimal> authid, string protocolNumber, string resultcode, string cpid)
        {
            var txidParameter = txid != null ?
                new ObjectParameter("txid", txid) :
                new ObjectParameter("txid", typeof(string));
    
            var serviceIdParameter = serviceId != null ?
                new ObjectParameter("serviceId", serviceId) :
                new ObjectParameter("serviceId", typeof(string));
    
            var operatorIdParameter = operatorId != null ?
                new ObjectParameter("operatorId", operatorId) :
                new ObjectParameter("operatorId", typeof(string));
    
            var categoryIdParameter = categoryId != null ?
                new ObjectParameter("categoryId", categoryId) :
                new ObjectParameter("categoryId", typeof(string));
    
            var msisdnParameter = msisdn != null ?
                new ObjectParameter("msisdn", msisdn) :
                new ObjectParameter("msisdn", typeof(string));
    
            var channelParameter = channel != null ?
                new ObjectParameter("channel", channel) :
                new ObjectParameter("channel", typeof(string));
    
            var authidParameter = authid.HasValue ?
                new ObjectParameter("authid", authid) :
                new ObjectParameter("authid", typeof(decimal));
    
            var protocolNumberParameter = protocolNumber != null ?
                new ObjectParameter("protocolNumber", protocolNumber) :
                new ObjectParameter("protocolNumber", typeof(string));
    
            var resultcodeParameter = resultcode != null ?
                new ObjectParameter("resultcode", resultcode) :
                new ObjectParameter("resultcode", typeof(string));
    
            var cpidParameter = cpid != null ?
                new ObjectParameter("cpid", cpid) :
                new ObjectParameter("cpid", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ins_eng_sub", txidParameter, serviceIdParameter, operatorIdParameter, categoryIdParameter, msisdnParameter, channelParameter, authidParameter, protocolNumberParameter, resultcodeParameter, cpidParameter);
        }
    
        public virtual int sp_ins_perums_charge(Nullable<decimal> id_sub, ObjectParameter id)
        {
            var id_subParameter = id_sub.HasValue ?
                new ObjectParameter("id_sub", id_sub) :
                new ObjectParameter("id_sub", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ins_perums_charge", id_subParameter, id);
        }
    
        public virtual int sp_ins_perums_charge_claro(string username, Nullable<decimal> msisdn, string billingCode, string responseCode, ObjectParameter id)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("username", username) :
                new ObjectParameter("username", typeof(string));
    
            var msisdnParameter = msisdn.HasValue ?
                new ObjectParameter("msisdn", msisdn) :
                new ObjectParameter("msisdn", typeof(decimal));
    
            var billingCodeParameter = billingCode != null ?
                new ObjectParameter("billingCode", billingCode) :
                new ObjectParameter("billingCode", typeof(string));
    
            var responseCodeParameter = responseCode != null ?
                new ObjectParameter("responseCode", responseCode) :
                new ObjectParameter("responseCode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ins_perums_charge_claro", usernameParameter, msisdnParameter, billingCodeParameter, responseCodeParameter, id);
        }
    
        public virtual int sp_ins_perums_sub(Nullable<decimal> id_user, Nullable<decimal> operador, Nullable<decimal> msisdn, Nullable<decimal> serviceCode, Nullable<decimal> subserviceCode, string content_id, string state, ObjectParameter id)
        {
            var id_userParameter = id_user.HasValue ?
                new ObjectParameter("id_user", id_user) :
                new ObjectParameter("id_user", typeof(decimal));
    
            var operadorParameter = operador.HasValue ?
                new ObjectParameter("operador", operador) :
                new ObjectParameter("operador", typeof(decimal));
    
            var msisdnParameter = msisdn.HasValue ?
                new ObjectParameter("msisdn", msisdn) :
                new ObjectParameter("msisdn", typeof(decimal));
    
            var serviceCodeParameter = serviceCode.HasValue ?
                new ObjectParameter("serviceCode", serviceCode) :
                new ObjectParameter("serviceCode", typeof(decimal));
    
            var subserviceCodeParameter = subserviceCode.HasValue ?
                new ObjectParameter("subserviceCode", subserviceCode) :
                new ObjectParameter("subserviceCode", typeof(decimal));
    
            var content_idParameter = content_id != null ?
                new ObjectParameter("content_id", content_id) :
                new ObjectParameter("content_id", typeof(string));
    
            var stateParameter = state != null ?
                new ObjectParameter("state", state) :
                new ObjectParameter("state", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ins_perums_sub", id_userParameter, operadorParameter, msisdnParameter, serviceCodeParameter, subserviceCodeParameter, content_idParameter, stateParameter, id);
        }
    
        public virtual int sp_ins_sia_transaction(Nullable<decimal> id_user, string id_usertxid, Nullable<decimal> id_operator, string id_rating, string contentId, string contentName, Nullable<decimal> msisdn, string url_ok, string url_cancel, string url_error, string url_unsuc, string extraparam, string txtype, ObjectParameter id_tx)
        {
            var id_userParameter = id_user.HasValue ?
                new ObjectParameter("id_user", id_user) :
                new ObjectParameter("id_user", typeof(decimal));
    
            var id_usertxidParameter = id_usertxid != null ?
                new ObjectParameter("id_usertxid", id_usertxid) :
                new ObjectParameter("id_usertxid", typeof(string));
    
            var id_operatorParameter = id_operator.HasValue ?
                new ObjectParameter("id_operator", id_operator) :
                new ObjectParameter("id_operator", typeof(decimal));
    
            var id_ratingParameter = id_rating != null ?
                new ObjectParameter("id_rating", id_rating) :
                new ObjectParameter("id_rating", typeof(string));
    
            var contentIdParameter = contentId != null ?
                new ObjectParameter("contentId", contentId) :
                new ObjectParameter("contentId", typeof(string));
    
            var contentNameParameter = contentName != null ?
                new ObjectParameter("contentName", contentName) :
                new ObjectParameter("contentName", typeof(string));
    
            var msisdnParameter = msisdn.HasValue ?
                new ObjectParameter("msisdn", msisdn) :
                new ObjectParameter("msisdn", typeof(decimal));
    
            var url_okParameter = url_ok != null ?
                new ObjectParameter("url_ok", url_ok) :
                new ObjectParameter("url_ok", typeof(string));
    
            var url_cancelParameter = url_cancel != null ?
                new ObjectParameter("url_cancel", url_cancel) :
                new ObjectParameter("url_cancel", typeof(string));
    
            var url_errorParameter = url_error != null ?
                new ObjectParameter("url_error", url_error) :
                new ObjectParameter("url_error", typeof(string));
    
            var url_unsucParameter = url_unsuc != null ?
                new ObjectParameter("url_unsuc", url_unsuc) :
                new ObjectParameter("url_unsuc", typeof(string));
    
            var extraparamParameter = extraparam != null ?
                new ObjectParameter("extraparam", extraparam) :
                new ObjectParameter("extraparam", typeof(string));
    
            var txtypeParameter = txtype != null ?
                new ObjectParameter("txtype", txtype) :
                new ObjectParameter("txtype", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ins_sia_transaction", id_userParameter, id_usertxidParameter, id_operatorParameter, id_ratingParameter, contentIdParameter, contentNameParameter, msisdnParameter, url_okParameter, url_cancelParameter, url_errorParameter, url_unsucParameter, extraparamParameter, txtypeParameter, id_tx);
        }
    
        public virtual int sp_mlk_ins_sms(Nullable<decimal> msisdn, string msg, ObjectParameter id)
        {
            var msisdnParameter = msisdn.HasValue ?
                new ObjectParameter("msisdn", msisdn) :
                new ObjectParameter("msisdn", typeof(decimal));
    
            var msgParameter = msg != null ?
                new ObjectParameter("msg", msg) :
                new ObjectParameter("msg", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_mlk_ins_sms", msisdnParameter, msgParameter, id);
        }
    
        public virtual int sp_perums_getChargeToSend()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_perums_getChargeToSend");
        }
    
        public virtual ObjectResult<sp_perums_getStats_Result> sp_perums_getStats(Nullable<decimal> selected_year, Nullable<decimal> selected_month)
        {
            var selected_yearParameter = selected_year.HasValue ?
                new ObjectParameter("selected_year", selected_year) :
                new ObjectParameter("selected_year", typeof(decimal));
    
            var selected_monthParameter = selected_month.HasValue ?
                new ObjectParameter("selected_month", selected_month) :
                new ObjectParameter("selected_month", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_perums_getStats_Result>("sp_perums_getStats", selected_yearParameter, selected_monthParameter);
        }
    
        public virtual ObjectResult<sp_perums_getStats_month_Result> sp_perums_getStats_month(Nullable<decimal> year, Nullable<decimal> mes, string subservice_code)
        {
            var yearParameter = year.HasValue ?
                new ObjectParameter("year", year) :
                new ObjectParameter("year", typeof(decimal));
    
            var mesParameter = mes.HasValue ?
                new ObjectParameter("mes", mes) :
                new ObjectParameter("mes", typeof(decimal));
    
            var subservice_codeParameter = subservice_code != null ?
                new ObjectParameter("subservice_code", subservice_code) :
                new ObjectParameter("subservice_code", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_perums_getStats_month_Result>("sp_perums_getStats_month", yearParameter, mesParameter, subservice_codeParameter);
        }
    
        public virtual int sp_renamediagram(string diagramname, Nullable<int> owner_id, string new_diagramname)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var new_diagramnameParameter = new_diagramname != null ?
                new ObjectParameter("new_diagramname", new_diagramname) :
                new ObjectParameter("new_diagramname", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_renamediagram", diagramnameParameter, owner_idParameter, new_diagramnameParameter);
        }
    
        public virtual ObjectResult<sp_renew_claro_dr_amigos_Result> sp_renew_claro_dr_amigos()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_renew_claro_dr_amigos_Result>("sp_renew_claro_dr_amigos");
        }
    
        public virtual ObjectResult<sp_rpt_comcel_Result> sp_rpt_comcel(Nullable<decimal> mes)
        {
            var mesParameter = mes.HasValue ?
                new ObjectParameter("mes", mes) :
                new ObjectParameter("mes", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_rpt_comcel_Result>("sp_rpt_comcel", mesParameter);
        }
    
        public virtual ObjectResult<sp_rpt_comcel_month_Result> sp_rpt_comcel_month(Nullable<decimal> mes)
        {
            var mesParameter = mes.HasValue ?
                new ObjectParameter("mes", mes) :
                new ObjectParameter("mes", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_rpt_comcel_month_Result>("sp_rpt_comcel_month", mesParameter);
        }
    
        public virtual ObjectResult<sp_rpt_comcel2_Result> sp_rpt_comcel2(Nullable<decimal> mes)
        {
            var mesParameter = mes.HasValue ?
                new ObjectParameter("mes", mes) :
                new ObjectParameter("mes", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_rpt_comcel2_Result>("sp_rpt_comcel2", mesParameter);
        }
    
        public virtual ObjectResult<sp_rpt_eng_Result> sp_rpt_eng()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_rpt_eng_Result>("sp_rpt_eng");
        }
    
        public virtual ObjectResult<sp_rpt_eng_month_Result> sp_rpt_eng_month()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_rpt_eng_month_Result>("sp_rpt_eng_month");
        }
    
        public virtual ObjectResult<sp_rpt_pb_Result> sp_rpt_pb()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_rpt_pb_Result>("sp_rpt_pb");
        }
    
        public virtual ObjectResult<sp_rpt_peekaboo_rpt_Result> sp_rpt_peekaboo_rpt(Nullable<int> m, Nullable<int> y)
        {
            var mParameter = m.HasValue ?
                new ObjectParameter("m", m) :
                new ObjectParameter("m", typeof(int));
    
            var yParameter = y.HasValue ?
                new ObjectParameter("y", y) :
                new ObjectParameter("y", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_rpt_peekaboo_rpt_Result>("sp_rpt_peekaboo_rpt", mParameter, yParameter);
        }
    
        public virtual ObjectResult<sp_rpt_peekaboo_rpt_day_Result> sp_rpt_peekaboo_rpt_day(Nullable<int> m, Nullable<int> y)
        {
            var mParameter = m.HasValue ?
                new ObjectParameter("m", m) :
                new ObjectParameter("m", typeof(int));
    
            var yParameter = y.HasValue ?
                new ObjectParameter("y", y) :
                new ObjectParameter("y", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_rpt_peekaboo_rpt_day_Result>("sp_rpt_peekaboo_rpt_day", mParameter, yParameter);
        }
    
        public virtual ObjectResult<sp_rpt_peekaboo_rpt_month_Result> sp_rpt_peekaboo_rpt_month(Nullable<int> y)
        {
            var yParameter = y.HasValue ?
                new ObjectParameter("y", y) :
                new ObjectParameter("y", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_rpt_peekaboo_rpt_month_Result>("sp_rpt_peekaboo_rpt_month", yParameter);
        }
    
        public virtual ObjectResult<sp_rpt_peekaboo_rpt_year_Result> sp_rpt_peekaboo_rpt_year(Nullable<int> y)
        {
            var yParameter = y.HasValue ?
                new ObjectParameter("y", y) :
                new ObjectParameter("y", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_rpt_peekaboo_rpt_year_Result>("sp_rpt_peekaboo_rpt_year", yParameter);
        }
    
        public virtual ObjectResult<sp_rpt_sia_Result> sp_rpt_sia()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_rpt_sia_Result>("sp_rpt_sia");
        }
    
        public virtual ObjectResult<sp_rpt_sia_month_Result> sp_rpt_sia_month()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_rpt_sia_month_Result>("sp_rpt_sia_month");
        }
    
        public virtual ObjectResult<sp_sia_rpt_Result> sp_sia_rpt(Nullable<decimal> mes, Nullable<decimal> año)
        {
            var mesParameter = mes.HasValue ?
                new ObjectParameter("mes", mes) :
                new ObjectParameter("mes", typeof(decimal));
    
            var añoParameter = año.HasValue ?
                new ObjectParameter("año", año) :
                new ObjectParameter("año", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_sia_rpt_Result>("sp_sia_rpt", mesParameter, añoParameter);
        }
    
        public virtual ObjectResult<sp_sia_rpt_detail_Result> sp_sia_rpt_detail(Nullable<decimal> mes, Nullable<decimal> año, Nullable<decimal> id_rating, Nullable<decimal> id_user)
        {
            var mesParameter = mes.HasValue ?
                new ObjectParameter("mes", mes) :
                new ObjectParameter("mes", typeof(decimal));
    
            var añoParameter = año.HasValue ?
                new ObjectParameter("año", año) :
                new ObjectParameter("año", typeof(decimal));
    
            var id_ratingParameter = id_rating.HasValue ?
                new ObjectParameter("id_rating", id_rating) :
                new ObjectParameter("id_rating", typeof(decimal));
    
            var id_userParameter = id_user.HasValue ?
                new ObjectParameter("id_user", id_user) :
                new ObjectParameter("id_user", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_sia_rpt_detail_Result>("sp_sia_rpt_detail", mesParameter, añoParameter, id_ratingParameter, id_userParameter);
        }
    
        public virtual ObjectResult<sp_sia_rpt_detail_dst_Result> sp_sia_rpt_detail_dst(Nullable<decimal> mes, Nullable<decimal> año, Nullable<decimal> id_rating, Nullable<decimal> id_user)
        {
            var mesParameter = mes.HasValue ?
                new ObjectParameter("mes", mes) :
                new ObjectParameter("mes", typeof(decimal));
    
            var añoParameter = año.HasValue ?
                new ObjectParameter("año", año) :
                new ObjectParameter("año", typeof(decimal));
    
            var id_ratingParameter = id_rating.HasValue ?
                new ObjectParameter("id_rating", id_rating) :
                new ObjectParameter("id_rating", typeof(decimal));
    
            var id_userParameter = id_user.HasValue ?
                new ObjectParameter("id_user", id_user) :
                new ObjectParameter("id_user", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_sia_rpt_detail_dst_Result>("sp_sia_rpt_detail_dst", mesParameter, añoParameter, id_ratingParameter, id_userParameter);
        }
    
        public virtual ObjectResult<sp_sia_rpt_dst_Result> sp_sia_rpt_dst(Nullable<decimal> mes, Nullable<decimal> año)
        {
            var mesParameter = mes.HasValue ?
                new ObjectParameter("mes", mes) :
                new ObjectParameter("mes", typeof(decimal));
    
            var añoParameter = año.HasValue ?
                new ObjectParameter("año", año) :
                new ObjectParameter("año", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_sia_rpt_dst_Result>("sp_sia_rpt_dst", mesParameter, añoParameter);
        }
    
        public virtual ObjectResult<sp_sia_status_Result> sp_sia_status(Nullable<decimal> mes)
        {
            var mesParameter = mes.HasValue ?
                new ObjectParameter("mes", mes) :
                new ObjectParameter("mes", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_sia_status_Result>("sp_sia_status", mesParameter);
        }
    
        public virtual int sp_sms_ins_mo(Nullable<decimal> id_sc, string msg, Nullable<decimal> msisdn, ObjectParameter id_mo)
        {
            var id_scParameter = id_sc.HasValue ?
                new ObjectParameter("id_sc", id_sc) :
                new ObjectParameter("id_sc", typeof(decimal));
    
            var msgParameter = msg != null ?
                new ObjectParameter("msg", msg) :
                new ObjectParameter("msg", typeof(string));
    
            var msisdnParameter = msisdn.HasValue ?
                new ObjectParameter("msisdn", msisdn) :
                new ObjectParameter("msisdn", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_sms_ins_mo", id_scParameter, msgParameter, msisdnParameter, id_mo);
        }
    
        public virtual int sp_sms_ins_mo_deliver(Nullable<decimal> id_mo, Nullable<decimal> id_url, Nullable<short> http_status)
        {
            var id_moParameter = id_mo.HasValue ?
                new ObjectParameter("id_mo", id_mo) :
                new ObjectParameter("id_mo", typeof(decimal));
    
            var id_urlParameter = id_url.HasValue ?
                new ObjectParameter("id_url", id_url) :
                new ObjectParameter("id_url", typeof(decimal));
    
            var http_statusParameter = http_status.HasValue ?
                new ObjectParameter("http_status", http_status) :
                new ObjectParameter("http_status", typeof(short));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_sms_ins_mo_deliver", id_moParameter, id_urlParameter, http_statusParameter);
        }
    
        public virtual int sp_sms_ins_mt(string id_ex, Nullable<decimal> id_user, Nullable<decimal> msisdn, string msg, string title, Nullable<decimal> id_sc, string smstype, ObjectParameter id)
        {
            var id_exParameter = id_ex != null ?
                new ObjectParameter("id_ex", id_ex) :
                new ObjectParameter("id_ex", typeof(string));
    
            var id_userParameter = id_user.HasValue ?
                new ObjectParameter("id_user", id_user) :
                new ObjectParameter("id_user", typeof(decimal));
    
            var msisdnParameter = msisdn.HasValue ?
                new ObjectParameter("msisdn", msisdn) :
                new ObjectParameter("msisdn", typeof(decimal));
    
            var msgParameter = msg != null ?
                new ObjectParameter("msg", msg) :
                new ObjectParameter("msg", typeof(string));
    
            var titleParameter = title != null ?
                new ObjectParameter("title", title) :
                new ObjectParameter("title", typeof(string));
    
            var id_scParameter = id_sc.HasValue ?
                new ObjectParameter("id_sc", id_sc) :
                new ObjectParameter("id_sc", typeof(decimal));
    
            var smstypeParameter = smstype != null ?
                new ObjectParameter("smstype", smstype) :
                new ObjectParameter("smstype", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_sms_ins_mt", id_exParameter, id_userParameter, msisdnParameter, msgParameter, titleParameter, id_scParameter, smstypeParameter, id);
        }
    
        public virtual int sp_sms_ins_mt_resp(string id_ex, Nullable<decimal> id_user, Nullable<decimal> msisdn, string msg, string title, Nullable<decimal> id_sc, string smstype, Nullable<byte> smstate, ObjectParameter id)
        {
            var id_exParameter = id_ex != null ?
                new ObjectParameter("id_ex", id_ex) :
                new ObjectParameter("id_ex", typeof(string));
    
            var id_userParameter = id_user.HasValue ?
                new ObjectParameter("id_user", id_user) :
                new ObjectParameter("id_user", typeof(decimal));
    
            var msisdnParameter = msisdn.HasValue ?
                new ObjectParameter("msisdn", msisdn) :
                new ObjectParameter("msisdn", typeof(decimal));
    
            var msgParameter = msg != null ?
                new ObjectParameter("msg", msg) :
                new ObjectParameter("msg", typeof(string));
    
            var titleParameter = title != null ?
                new ObjectParameter("title", title) :
                new ObjectParameter("title", typeof(string));
    
            var id_scParameter = id_sc.HasValue ?
                new ObjectParameter("id_sc", id_sc) :
                new ObjectParameter("id_sc", typeof(decimal));
    
            var smstypeParameter = smstype != null ?
                new ObjectParameter("smstype", smstype) :
                new ObjectParameter("smstype", typeof(string));
    
            var smstateParameter = smstate.HasValue ?
                new ObjectParameter("smstate", smstate) :
                new ObjectParameter("smstate", typeof(byte));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_sms_ins_mt_resp", id_exParameter, id_userParameter, msisdnParameter, msgParameter, titleParameter, id_scParameter, smstypeParameter, smstateParameter, id);
        }
    
        public virtual int sp_sms_toSend(Nullable<decimal> id_sc)
        {
            var id_scParameter = id_sc.HasValue ?
                new ObjectParameter("id_sc", id_sc) :
                new ObjectParameter("id_sc", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_sms_toSend", id_scParameter);
        }
    
        public virtual int sp_spr_insMo(string phone, Nullable<int> shortNum, string msgText, Nullable<decimal> msgId, string userp, string pwd, Nullable<int> idOperator, string enc, string refMsgId, ObjectParameter id)
        {
            var phoneParameter = phone != null ?
                new ObjectParameter("phone", phone) :
                new ObjectParameter("phone", typeof(string));
    
            var shortNumParameter = shortNum.HasValue ?
                new ObjectParameter("shortNum", shortNum) :
                new ObjectParameter("shortNum", typeof(int));
    
            var msgTextParameter = msgText != null ?
                new ObjectParameter("msgText", msgText) :
                new ObjectParameter("msgText", typeof(string));
    
            var msgIdParameter = msgId.HasValue ?
                new ObjectParameter("msgId", msgId) :
                new ObjectParameter("msgId", typeof(decimal));
    
            var userpParameter = userp != null ?
                new ObjectParameter("userp", userp) :
                new ObjectParameter("userp", typeof(string));
    
            var pwdParameter = pwd != null ?
                new ObjectParameter("pwd", pwd) :
                new ObjectParameter("pwd", typeof(string));
    
            var idOperatorParameter = idOperator.HasValue ?
                new ObjectParameter("idOperator", idOperator) :
                new ObjectParameter("idOperator", typeof(int));
    
            var encParameter = enc != null ?
                new ObjectParameter("enc", enc) :
                new ObjectParameter("enc", typeof(string));
    
            var refMsgIdParameter = refMsgId != null ?
                new ObjectParameter("refMsgId", refMsgId) :
                new ObjectParameter("refMsgId", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_spr_insMo", phoneParameter, shortNumParameter, msgTextParameter, msgIdParameter, userpParameter, pwdParameter, idOperatorParameter, encParameter, refMsgIdParameter, id);
        }
    
        public virtual int sp_upgraddiagrams()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_upgraddiagrams");
        }
    
        public virtual ObjectResult<sp_get_user_operator_Result> sp_get_user_operator(Nullable<decimal> id_user)
        {
            var id_userParameter = id_user.HasValue ?
                new ObjectParameter("id_user", id_user) :
                new ObjectParameter("id_user", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_get_user_operator_Result>("sp_get_user_operator", id_userParameter);
        }
    
        public virtual ObjectResult<sp_stats_getMovistarMonthByUser_Result> sp_stats_getMovistarMonthByUser(Nullable<decimal> id_user, Nullable<decimal> selected_year, Nullable<decimal> selected_month)
        {
            var id_userParameter = id_user.HasValue ?
                new ObjectParameter("id_user", id_user) :
                new ObjectParameter("id_user", typeof(decimal));
    
            var selected_yearParameter = selected_year.HasValue ?
                new ObjectParameter("selected_year", selected_year) :
                new ObjectParameter("selected_year", typeof(decimal));
    
            var selected_monthParameter = selected_month.HasValue ?
                new ObjectParameter("selected_month", selected_month) :
                new ObjectParameter("selected_month", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_stats_getMovistarMonthByUser_Result>("sp_stats_getMovistarMonthByUser", id_userParameter, selected_yearParameter, selected_monthParameter);
        }
    }
}
