//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EndeavorlinkStats.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_sia_billing
    {
        public decimal id { get; set; }
        public decimal id_tx_r { get; set; }
        public decimal id_tx_s { get; set; }
        public System.DateTime fecha_hora { get; set; }
    }
}
