//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EndeavorlinkStats.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_smt_serviceid
    {
        public decimal id { get; set; }
        public string mdsp { get; set; }
        public string serviceid { get; set; }
        public string description { get; set; }
        public decimal id_user { get; set; }
        public decimal productid { get; set; }
        public string callbackUrl { get; set; }
    }
}
