//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EndeavorlinkStats.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_peru_ml_subcription
    {
        public decimal id_sub { get; set; }
        public decimal id_user { get; set; }
        public System.DateTime create_date { get; set; }
        public decimal operador { get; set; }
        public decimal msisdn { get; set; }
        public string service_code { get; set; }
        public string subservice_code { get; set; }
        public string content_id { get; set; }
        public string state { get; set; }
    }
}
