//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EndeavorlinkStats.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_sms_sc
    {
        public tbl_sms_sc()
        {
            this.tbl_sms_mo = new HashSet<tbl_sms_mo>();
            this.tbl_sms_mt = new HashSet<tbl_sms_mt>();
        }
    
        public decimal id_sc { get; set; }
        public decimal id_operator { get; set; }
        public string sc { get; set; }
    
        public virtual tbl_operator tbl_operator { get; set; }
        public virtual tbl_operator tbl_operator1 { get; set; }
        public virtual ICollection<tbl_sms_mo> tbl_sms_mo { get; set; }
        public virtual ICollection<tbl_sms_mt> tbl_sms_mt { get; set; }
    }
}
