//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EndeavorlinkStats.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_peru_ml_charge
    {
        public decimal id_charge { get; set; }
        public decimal id_sub { get; set; }
        public System.DateTime create_date { get; set; }
        public string respcode { get; set; }
        public Nullable<decimal> state { get; set; }
    }
}
