//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EndeavorlinkStats.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_amdocs_device2
    {
        public decimal id_device { get; set; }
        public string brand { get; set; }
        public string model { get; set; }
        public string deviceid { get; set; }
        public string xml { get; set; }
        public bool top100 { get; set; }
        public Nullable<int> ordtop100 { get; set; }
    }
}
