//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EndeavorlinkStats.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_charge_peru
    {
        public decimal id_charge { get; set; }
        public System.DateTime create_date { get; set; }
        public string respcode { get; set; }
        public decimal state { get; set; }
        public decimal id_user { get; set; }
        public decimal operador { get; set; }
        public decimal msisdn { get; set; }
        public string service_code { get; set; }
        public string subservice_code { get; set; }
        public string content_id { get; set; }
        public Nullable<decimal> partnerTxID { get; set; }
    }
}
