//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EndeavorlinkStats.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_eng_subscription
    {
        public decimal id { get; set; }
        public string txid { get; set; }
        public string serviceId { get; set; }
        public string @operator { get; set; }
        public string categoryId { get; set; }
        public string msisdn { get; set; }
        public string channel { get; set; }
        public decimal authid { get; set; }
        public string protocolNumber { get; set; }
        public string resultcode { get; set; }
        public System.DateTime createdate { get; set; }
        public string sub_status { get; set; }
        public Nullable<System.DateTime> last_renew { get; set; }
        public Nullable<int> renew_count { get; set; }
        public Nullable<System.DateTime> next_renew { get; set; }
        public Nullable<short> oneshot { get; set; }
        public string cpid { get; set; }
        public string urlsub { get; set; }
    }
}
