//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EndeavorlinkStats.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_eng_charge
    {
        public decimal idcharge { get; set; }
        public string txid { get; set; }
        public string serviceId { get; set; }
        public decimal authid { get; set; }
        public string cents { get; set; }
        public string chargeReason { get; set; }
        public string resultcode { get; set; }
        public System.DateTime createdate { get; set; }
    }
}
