//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EndeavorlinkStats.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_hub_sync
    {
        public decimal id_sync { get; set; }
        public System.DateTime create_date { get; set; }
        public string msisdn { get; set; }
        public string spID { get; set; }
        public string serviceID { get; set; }
        public string updateType { get; set; }
        public string rentResult { get; set; }
    }
}
