//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EndeavorlinkStats.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_comcel_sub
    {
        public decimal id { get; set; }
        public decimal id_user { get; set; }
        public string idcp { get; set; }
        public decimal msisdn { get; set; }
        public decimal serviceCode { get; set; }
        public decimal providerCode { get; set; }
        public string sub_status { get; set; }
        public System.DateTime createdate { get; set; }
        public System.DateTime lastrenew { get; set; }
    }
}
