//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EndeavorlinkStats.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_eng_mt
    {
        public decimal id_mt { get; set; }
        public System.DateTime create_date { get; set; }
        public string txid { get; set; }
        public string operatorId { get; set; }
        public string serviceId { get; set; }
        public string categoryId { get; set; }
        public string authId { get; set; }
        public string msisdn { get; set; }
        public string caringType { get; set; }
        public string text { get; set; }
    }
}
