//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EndeavorlinkStats.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_smt_sub
    {
        public decimal id_sub { get; set; }
        public string idex { get; set; }
        public string msisdn { get; set; }
        public System.DateTime create_date { get; set; }
        public string substatus { get; set; }
        public string url { get; set; }
        public string sid { get; set; }
    }
}
