//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EndeavorlinkStats.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_sms_mt_log
    {
        public decimal id_mt { get; set; }
        public string idex { get; set; }
        public decimal id_user { get; set; }
        public decimal msisdn { get; set; }
        public string msg { get; set; }
        public string title { get; set; }
        public byte smsstate { get; set; }
        public decimal id_sc { get; set; }
        public string smstype { get; set; }
        public Nullable<System.DateTime> create_date { get; set; }
    }
}
