//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EndeavorlinkStats.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_purebros_bill
    {
        public decimal id_bill { get; set; }
        public string msisnd { get; set; }
        public System.DateTime create_date { get; set; }
        public string resp { get; set; }
    }
}
