//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EndeavorlinkStats.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_operator
    {
        public tbl_operator()
        {
            this.tbl_sms_sc = new HashSet<tbl_sms_sc>();
            this.tbl_sms_sc1 = new HashSet<tbl_sms_sc>();
        }
    
        public decimal id_operator { get; set; }
        public string name { get; set; }
        public Nullable<decimal> id_pais { get; set; }
    
        public virtual ICollection<tbl_sms_sc> tbl_sms_sc { get; set; }
        public virtual ICollection<tbl_sms_sc> tbl_sms_sc1 { get; set; }
    }
}
