//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EndeavorlinkStats.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_cp_callback
    {
        public decimal id { get; set; }
        public decimal id_cp { get; set; }
        public string callback { get; set; }
    
        public virtual tbl_content_provider tbl_content_provider { get; set; }
    }
}
