//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EndeavorlinkStats.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_spr_insMt
    {
        public decimal id_mt { get; set; }
        public string userp { get; set; }
        public string pwd { get; set; }
        public string appdid { get; set; }
        public string enc { get; set; }
        public Nullable<byte> id_mtStatus { get; set; }
        public System.DateTime tstamp { get; set; }
    
        public virtual tbl_spr_mtStatus tbl_spr_mtStatus { get; set; }
    }
}
