//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EndeavorlinkStats.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_pais
    {
        public tbl_pais()
        {
            this.tbl_operator = new HashSet<tbl_operator>();
        }
    
        public decimal id_pais { get; set; }
        public string name { get; set; }
    
        public virtual ICollection<tbl_operator> tbl_operator { get; set; }
    }
}
