//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EndeavorlinkStats.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ml_sms_prices
    {
        public decimal id { get; set; }
        public string reg { get; set; }
        public string country { get; set; }
        public string network { get; set; }
        public decimal r1 { get; set; }
        public decimal r2 { get; set; }
        public decimal r3 { get; set; }
        public decimal r4 { get; set; }
        public decimal r5 { get; set; }
        public decimal r6 { get; set; }
        public decimal profit { get; set; }
    }
}
