//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EndeavorlinkStats.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_spr_mtStatus
    {
        public tbl_spr_mtStatus()
        {
            this.tbl_spr_insMt = new HashSet<tbl_spr_insMt>();
        }
    
        public byte id_mtStatus { get; set; }
        public string descripcion { get; set; }
        public System.DateTime tstamp { get; set; }
    
        public virtual ICollection<tbl_spr_insMt> tbl_spr_insMt { get; set; }
    }
}
