//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EndeavorlinkStats.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_eng_unsub_notification
    {
        public decimal id { get; set; }
        public System.DateTime createdate { get; set; }
        public string txId { get; set; }
        public string opType { get; set; }
        public string channel { get; set; }
        public string msisdn { get; set; }
        public string authId { get; set; }
    }
}
