//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EndeavorlinkStats.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_mlk_sms
    {
        public decimal id { get; set; }
        public decimal msisdn { get; set; }
        public string msg { get; set; }
        public decimal status { get; set; }
        public Nullable<decimal> deliver { get; set; }
        public Nullable<decimal> sentstatus { get; set; }
        public System.DateTime create_date { get; set; }
    }
}
