//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EndeavorlinkStats.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_purebros_mo
    {
        public decimal id_mo { get; set; }
        public decimal id_pbmo { get; set; }
        public decimal msisdn { get; set; }
        public string msg { get; set; }
        public string errCode { get; set; }
        public string authorizationId { get; set; }
        public string subscriptionId { get; set; }
        public string requestId { get; set; }
        public string callCenterProtocol { get; set; }
        public Nullable<System.DateTime> fecha_hora { get; set; }
        public string tx_status { get; set; }
        public string servtype { get; set; }
        public string crd_chk_error { get; set; }
        public string bill_error { get; set; }
        public string carrier { get; set; }
    }
}
