//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EndeavorlinkStats.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_pkaboo_hit
    {
        public decimal id { get; set; }
        public string providerKey { get; set; }
        public string pbId { get; set; }
        public string msisdn { get; set; }
        public System.DateTime createdate { get; set; }
        public string cz { get; set; }
    }
}
