//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EndeavorlinkStats.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_sia_distinct_transaction
    {
        public decimal id { get; set; }
        public decimal msisdn { get; set; }
        public decimal id_rating { get; set; }
        public decimal id_user { get; set; }
        public decimal id_transaction { get; set; }
    
        public virtual tbl_sia_transaction tbl_sia_transaction { get; set; }
    }
}
