//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EndeavorlinkStats.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_sms_mo_deliver
    {
        public decimal id_deliver { get; set; }
        public decimal id_mo { get; set; }
        public decimal id_url { get; set; }
        public short http_status { get; set; }
        public System.DateTime create_date { get; set; }
    
        public virtual tbl_sms_mo tbl_sms_mo { get; set; }
        public virtual tbl_sms_sc_url tbl_sms_sc_url { get; set; }
    }
}
