//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EndeavorlinkStats.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_gm_catalog
    {
        public decimal id_game { get; set; }
        public string title { get; set; }
        public string descrip { get; set; }
        public string platforms { get; set; }
        public string picture { get; set; }
    }
}
