//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EndeavorlinkStats.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_SFM
    {
        public string msisdn { get; set; }
        public string UA { get; set; }
        public System.DateTime cd { get; set; }
        public System.DateTime lr { get; set; }
    }
}
