//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EndeavorlinkStats.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_spr_operator
    {
        public tbl_spr_operator()
        {
            this.tbl_spr_mo = new HashSet<tbl_spr_mo>();
        }
    
        public int idOperator { get; set; }
        public string name { get; set; }
        public System.DateTime tstamp { get; set; }
    
        public virtual ICollection<tbl_spr_mo> tbl_spr_mo { get; set; }
    }
}
