//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EndeavorlinkStats.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_spr_billing
    {
        public decimal id_billing { get; set; }
        public string url { get; set; }
        public string port { get; set; }
        public string tarif_class { get; set; }
        public string content_type { get; set; }
        public string app_id { get; set; }
        public string typeb { get; set; }
        public System.DateTime tstamp { get; set; }
    }
}
