//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EndeavorlinkStats.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_sms_mo
    {
        public tbl_sms_mo()
        {
            this.tbl_sms_mo_deliver = new HashSet<tbl_sms_mo_deliver>();
        }
    
        public decimal id_mo { get; set; }
        public decimal id_sc { get; set; }
        public string msg { get; set; }
        public byte smsstate { get; set; }
        public decimal msisdn { get; set; }
        public Nullable<System.DateTime> create_date { get; set; }
    
        public virtual ICollection<tbl_sms_mo_deliver> tbl_sms_mo_deliver { get; set; }
        public virtual tbl_sms_sc tbl_sms_sc { get; set; }
        public virtual tbl_sms_mo tbl_sms_mo1 { get; set; }
        public virtual tbl_sms_mo tbl_sms_mo2 { get; set; }
    }
}
