//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EndeavorlinkStats.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_gm_xendex_amdocs
    {
        public string id_game { get; set; }
        public decimal id_xendex { get; set; }
        public decimal id_amdocs { get; set; }
        public System.DateTime create_date { get; set; }
    }
}
