//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EndeavorlinkStats.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_mt_extern
    {
        public decimal id { get; set; }
        public string idtx { get; set; }
        public string msisdn { get; set; }
        public string msg { get; set; }
        public string title { get; set; }
        public string sc { get; set; }
        public byte smstype { get; set; }
    }
}
