//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EndeavorlinkStats.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_fb_user
    {
        public decimal id { get; set; }
        public string token { get; set; }
        public decimal fbuser_id { get; set; }
        public System.DateTime create_date { get; set; }
        public System.DateTime expire { get; set; }
        public decimal app_status { get; set; }
        public string fb_status { get; set; }
        public decimal msisdn { get; set; }
    }
}
