//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EndeavorlinkStats.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_perums_callback
    {
        public decimal id_callback { get; set; }
        public decimal id_user { get; set; }
        public string calback_url { get; set; }
    
        public virtual tbl_user tbl_user { get; set; }
    }
}
