//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EndeavorlinkStats.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_comcel_charge
    {
        public decimal id { get; set; }
        public decimal id_user { get; set; }
        public string idcp { get; set; }
        public decimal msisdn { get; set; }
        public decimal servicecode { get; set; }
        public decimal providercode { get; set; }
        public decimal response { get; set; }
        public System.DateTime createdate { get; set; }
        public string contentid { get; set; }
        public string charge_type { get; set; }
    }
}
