//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EndeavorlinkStats.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_purebros_mt
    {
        public decimal id_mt { get; set; }
        public string msg { get; set; }
        public string msisdn { get; set; }
        public string sc { get; set; }
        public string carrier { get; set; }
        public string servtype { get; set; }
        public System.DateTime fecha_hora { get; set; }
        public string mt_id { get; set; }
    }
}
